server:
  port: 8001

spring:
  application:
    name: @project.artifactId@  #服务名称!
  profiles:
    active: @spring.profiles.active@
  zipkin:
    base-url: http://localhost:9411
  jackson:
    time-zone: UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  sleuth:
    sampler:
      #采样率值介于 0 到 1 之间，1 则表示全部采集
      probability: 1
app:
  version: "@project.version@"
  build:
    time: "@build.time@"
hystrix:
  command:
    serverMethod:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #      #单机版
      defaultZone: http://localhost:7001/eureka
      # 集群版
  #      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: @project.artifactId@
    #访问路径可以显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    lease-renewal-interval-in-seconds: 3
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    lease-expiration-duration-in-seconds: 2
logging:
  config: classpath:config/logback-spring.xml

mybatis-plus:
  type-aliases-package: com.scale.invest.api.model.*
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    refresh-mapper: true
    id-type: 0
    field-strategy: 1
    db-column-underline: true
    logic-delete-value: 0
    logic-not-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

feign:
  hystrix:
    enabled: true
